// Mocks generated by Mockito 5.4.2 from annotations
// in worktenser/test/projects/cubits/projects_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:worktenser/domain/authentication/models/user_model.dart' as _i5;
import 'package:worktenser/domain/projects/src/models/project_model.dart'
    as _i4;
import 'package:worktenser/domain/projects/src/repositories/iprojects_repository.dart'
    as _i2;
import 'package:worktenser/domain/projects/src/services/iprojects_local_storage.dart'
    as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [IProjectsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockIProjectsRepository extends _i1.Mock
    implements _i2.IProjectsRepository {
  @override
  _i3.Future<List<_i4.Project>> loadProjects(_i5.User? user) =>
      (super.noSuchMethod(
        Invocation.method(
          #loadProjects,
          [user],
        ),
        returnValue: _i3.Future<List<_i4.Project>>.value(<_i4.Project>[]),
        returnValueForMissingStub:
            _i3.Future<List<_i4.Project>>.value(<_i4.Project>[]),
      ) as _i3.Future<List<_i4.Project>>);
  @override
  _i3.Future<bool> addProject(_i4.Project? project) => (super.noSuchMethod(
        Invocation.method(
          #addProject,
          [project],
        ),
        returnValue: _i3.Future<bool>.value(false),
        returnValueForMissingStub: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);
  @override
  _i3.Future<bool> updateProject(_i4.Project? project) => (super.noSuchMethod(
        Invocation.method(
          #updateProject,
          [project],
        ),
        returnValue: _i3.Future<bool>.value(false),
        returnValueForMissingStub: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);
  @override
  _i3.Future<bool> deleteProject(_i4.Project? project) => (super.noSuchMethod(
        Invocation.method(
          #deleteProject,
          [project],
        ),
        returnValue: _i3.Future<bool>.value(false),
        returnValueForMissingStub: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);
}

/// A class which mocks [IProjectsLocalStorage].
///
/// See the documentation for Mockito's code generation for more information.
class MockIProjectsLocalStorage extends _i1.Mock
    implements _i6.IProjectsLocalStorage {
  @override
  List<_i4.Project> load() => (super.noSuchMethod(
        Invocation.method(
          #load,
          [],
        ),
        returnValue: <_i4.Project>[],
        returnValueForMissingStub: <_i4.Project>[],
      ) as List<_i4.Project>);
  @override
  _i3.Future<bool> save(List<_i4.Project>? projects) => (super.noSuchMethod(
        Invocation.method(
          #save,
          [projects],
        ),
        returnValue: _i3.Future<bool>.value(false),
        returnValueForMissingStub: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);
  @override
  _i3.Future<bool> update(_i4.Project? project) => (super.noSuchMethod(
        Invocation.method(
          #update,
          [project],
        ),
        returnValue: _i3.Future<bool>.value(false),
        returnValueForMissingStub: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);
  @override
  _i3.Future<bool> delete(_i4.Project? project) => (super.noSuchMethod(
        Invocation.method(
          #delete,
          [project],
        ),
        returnValue: _i3.Future<bool>.value(false),
        returnValueForMissingStub: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);
  @override
  _i3.Future<bool> clear() => (super.noSuchMethod(
        Invocation.method(
          #clear,
          [],
        ),
        returnValue: _i3.Future<bool>.value(false),
        returnValueForMissingStub: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);
}
