// Mocks generated by Mockito 5.4.2 from annotations
// in worktenser/test/features/projects/presentation/bloc/projects_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:worktenser/features/auth/domain/entities/user.dart' as _i5;
import 'package:worktenser/features/projects/domain/entities/project.dart'
    as _i4;
import 'package:worktenser/features/projects/domain/usecases/add_project.dart'
    as _i6;
import 'package:worktenser/features/projects/domain/usecases/delete_project.dart'
    as _i8;
import 'package:worktenser/features/projects/domain/usecases/get_projects_total_time.dart'
    as _i9;
import 'package:worktenser/features/projects/domain/usecases/load_projects.dart'
    as _i2;
import 'package:worktenser/features/projects/domain/usecases/update_project.dart'
    as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [LoadProjectsUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockLoadProjectsUsecase extends _i1.Mock
    implements _i2.LoadProjectsUsecase {
  @override
  _i3.Future<List<_i4.ProjectEntity>> call({_i5.UserEntity? params}) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
          {#params: params},
        ),
        returnValue:
            _i3.Future<List<_i4.ProjectEntity>>.value(<_i4.ProjectEntity>[]),
        returnValueForMissingStub:
            _i3.Future<List<_i4.ProjectEntity>>.value(<_i4.ProjectEntity>[]),
      ) as _i3.Future<List<_i4.ProjectEntity>>);
}

/// A class which mocks [AddProjectUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockAddProjectUseCase extends _i1.Mock implements _i6.AddProjectUseCase {
  @override
  _i3.Future<bool> call({_i4.ProjectEntity? params}) => (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
          {#params: params},
        ),
        returnValue: _i3.Future<bool>.value(false),
        returnValueForMissingStub: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);
}

/// A class which mocks [UpdateProjectUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockUpdateProjectUseCase extends _i1.Mock
    implements _i7.UpdateProjectUseCase {
  @override
  _i3.Future<bool> call({_i4.ProjectEntity? params}) => (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
          {#params: params},
        ),
        returnValue: _i3.Future<bool>.value(false),
        returnValueForMissingStub: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);
}

/// A class which mocks [DeleteProjectUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockDeleteProjectUseCase extends _i1.Mock
    implements _i8.DeleteProjectUseCase {
  @override
  _i3.Future<bool> call({_i4.ProjectEntity? params}) => (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
          {#params: params},
        ),
        returnValue: _i3.Future<bool>.value(false),
        returnValueForMissingStub: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);
}

/// A class which mocks [GetProjectsTotalTimeUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetProjectsTotalTimeUseCase extends _i1.Mock
    implements _i9.GetProjectsTotalTimeUseCase {
  @override
  _i3.Future<int> call({List<_i4.ProjectEntity>? params}) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
          {#params: params},
        ),
        returnValue: _i3.Future<int>.value(0),
        returnValueForMissingStub: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);
}
