// Mocks generated by Mockito 5.4.2 from annotations
// in worktenser/test/features/auth/presentation/bloc/login/login_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:worktenser/features/auth/domain/entities/login.dart' as _i4;
import 'package:worktenser/features/auth/domain/usecases/signin_with_credentials.dart'
    as _i2;
import 'package:worktenser/features/auth/domain/usecases/signin_with_google.dart'
    as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [SigninWithCredentialsUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockSigninWithCredentialsUseCase extends _i1.Mock
    implements _i2.SigninWithCredentialsUseCase {
  @override
  _i3.Future<bool> call({_i4.LoginEntity? params}) => (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
          {#params: params},
        ),
        returnValue: _i3.Future<bool>.value(false),
        returnValueForMissingStub: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);
}

/// A class which mocks [SigninWithGoogleUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockSigninWithGoogleUseCase extends _i1.Mock
    implements _i5.SigninWithGoogleUseCase {
  @override
  _i3.Future<bool> call({dynamic params}) => (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
          {#params: params},
        ),
        returnValue: _i3.Future<bool>.value(false),
        returnValueForMissingStub: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);
}
